"use client";

import { QRCodeSVG } from "qrcode.react";

/**
 * The scan-to-link affordance: one QR per channel, encoding a deep link that
 * carries the token (see utils/constants/messaging/links).
 *
 * Rendered CLIENT-side on purpose. The token is regenerated by a button in the
 * same panel, and a server-rendered QR would keep showing the previous code
 * until a round-trip landed — handing someone a QR that links nothing. This one
 * is a pure function of the token in state, so it can never disagree with the
 * code printed above it.
 *
 * Colours come from the qr-plate/qr-ink tokens, which are identical in light and
 * dark: ink/paper swap between themes, and an inverted QR is unreadable to a
 * good share of scanners.
 */
export function MessagingLinkQr({
  label,
  url,
  hint,
}: {
  label: string;
  url: string;
  hint: string;
}) {
  return (
    <div className="flex min-w-0 flex-1 flex-col items-center gap-2 rounded-lg border border-seam p-3">
      <p className="text-xs font-medium text-paper">{label}</p>
      <a
        href={url}
        target="_blank"
        rel="noopener noreferrer"
        // The QR is for another device; the tap target is for THIS one — the
        // person setting this up on their phone shouldn't have to scan a code
        // that's already in their hand.
        className="rounded-md bg-qr-plate p-2 outline-offset-2 focus-visible:outline focus-visible:outline-2 focus-visible:outline-amber"
        aria-label={`Open ${label} to link this chat`}
      >
        <QRCodeSVG value={url} size={112} bgColor="transparent" fgColor="var(--color-qr-ink)" />
      </a>
      <p className="text-center text-[11px] leading-snug text-fog">{hint}</p>
    </div>
  );
}
