// The LLM gateway half of the services barrel: clients, prompt builders and
// their context types. Split out of ../services.ts per the 150-line rule and
// re-exported wholesale by ./index.ts, so no import path changes.
export {
  AnthropicLLMClient,
  OpenAILLMClient,
  BRIEF_SYSTEM,
  CAPTURE_EXTRACTION_SYSTEM,
  CARD_SCAN_PROMPT,
  CARD_SCAN_SYSTEM,
  CARD_TRANSCRIPTION_PROMPT,
  CARD_TRANSCRIPTION_SYSTEM,
  BATCH_PLAN_SYSTEM,
  CONTACT_PARSE_SYSTEM,
  DRAFT_SYSTEM,
  ENRICHMENT_SYSTEM,
  ENRICHMENT_EXTRACTION_SYSTEM,
  NOTE_EXTRACTION_SYSTEM,
  SEARCH_ANSWER_SYSTEM,
  SEARCH_QUERY_SYSTEM,
  buildBatchPlanPrompt,
  buildBriefPrompt,
  buildContactParsePrompt,
  buildDraftPrompt,
  buildEnrichmentPrompt,
  buildEnrichmentExtractionPrompt,
  buildNoteExtractionPrompt,
  buildSearchAnswerPrompt,
  buildSearchQueryPrompt,
  type BatchPlanCandidate,
  type BatchPlanItem,
  type BriefContext,
  type DraftContext,
  type EnrichmentSubject,
  type NodeTypeRef,
  getBatchLLMClient,
  getLLMClient,
  getLLMProvider,
  hasBatchLLM,
  hasLLM,
  registerLLMProvider,
  selectLLMProvider,
  type BatchExtractItem,
  type BatchExtractResult,
  type BatchLLMClient,
  type BatchResultStatus,
  type CompleteOptions,
  type ExtractOptions,
  type LLMClient,
  type LLMImage,
  type LLMResult,
  type LLMUsage,
  type LLMProvider,
  type LLMProviderCapabilities,
  type ModelTier,
  type OpenAILLMClientOptions,
} from "../llm";
export { PHOTO_NOTE_PROMPT, PHOTO_NOTE_SYSTEM } from "../llm";
export {
  GOAL_MATCHING_SYSTEM,
  PERSON_CLASSIFICATION_SYSTEM,
  SIGNAL_DETECTION_SYSTEM,
  buildGoalMatchingPrompt,
  buildPersonClassificationPrompt,
  buildSignalDetectionPrompt,
  type GoalMatchingSubject,
  type PersonClassificationSubject,
  type SignalDetectionSubject,
} from "../llm";
