import { seedDomainAccount } from "../seed-lib/seed-domain.mjs";

await seedDomainAccount({
  slug: "b2b-sales",
  displayName: "Priya Nair — Account Executive (demo)",
  companies: [
    // Prospect / customer accounts across industries
    { name: "Cargoline Freight", sector: "Logistics" },
    { name: "Northwind Logistics", sector: "Logistics" },
    { name: "HelvetSecure", sector: "Cybersecurity" },
    { name: "Brightwell Health", sector: "Healthcare" },
    { name: "Meridian Retail Group", sector: "Retail" },
    { name: "Aldergrove Bank", sector: "Financial Services" },
    { name: "Solvent Manufacturing", sector: "Manufacturing" },
    { name: "Kestrel Aerospace", sector: "Aerospace" },
    { name: "Verdant Foods", sector: "Food & Beverage" },
    { name: "Pinecrest Insurance", sector: "Insurance" },
    { name: "Lumen Media", sector: "Media" },
    { name: "Tessellate Analytics", sector: "SaaS" },
    { name: "Ironbridge Utilities", sector: "Energy" },
    { name: "Harbor & Vale Legal", sector: "Legal" },
    // Partner vendors
    { name: "Coriander Systems Integrators", sector: "Consulting (Partner)" },
    { name: "Ridgeway Cloud Partners", sector: "Cloud Reseller (Partner)" },
  ],
  contacts: [
    // --- Cargoline Freight (key account, closed-won, multi-threaded) ---
    {
      name: "Dev Malhotra",
      title: "VP Engineering",
      company: "Cargoline Freight",
      location: "Chicago, IL",
      tags: ["champion", "closed-won"],
      note: "Champion — cares about onboarding time; moved from Northwind to Cargoline, warm re-intro.",
    },
    {
      name: "Sofia Reyes",
      title: "CFO",
      company: "Cargoline Freight",
      location: "Chicago, IL",
      tags: ["economic-buyer", "closed-won"],
      note: "EB — signed the annual deal; renewal expansion conversation for next fiscal.",
    },
    {
      name: "Grace Okonkwo",
      title: "Head of Ops",
      company: "Cargoline Freight",
      location: "Detroit, MI",
      tags: ["evaluator", "closed-won"],
      note: "Ran the operational pilot; strong internal advocate alongside Dev.",
    },
    {
      name: "Marcus Feld",
      title: "IT Procurement Lead",
      company: "Cargoline Freight",
      location: "Chicago, IL",
      tags: ["blocker"],
      note: "Pushed hard on security review timelines; neutralized after SOC2 packet shared.",
    },
    {
      name: "Aisha Bello",
      title: "Solutions Architect",
      company: "Cargoline Freight",
      location: "Remote",
      tags: ["evaluator"],
    },

    // --- Northwind Logistics (competitor unseated Dev; still active) ---
    {
      name: "Tomas Novak",
      title: "VP Operations",
      company: "Northwind Logistics",
      location: "Minneapolis, MN",
      tags: ["economic-buyer"],
      note: "EB — budget frees up next fiscal year; keep warm until Q3.",
    },
    {
      name: "Rebecca Lin",
      title: "Director of Engineering",
      company: "Northwind Logistics",
      location: "Minneapolis, MN",
      tags: ["evaluator"],
    },
    {
      name: "Owen Pratt",
      title: "Procurement Lead",
      company: "Northwind Logistics",
      location: "Chicago, IL",
      tags: ["blocker"],
      note: "Prefers incumbent vendor; needs a compelling switching-cost story.",
    },

    // --- HelvetSecure (cybersecurity prospect) ---
    {
      name: "Lena Fischer",
      title: "CISO",
      company: "HelvetSecure",
      location: "Zurich, CH",
      tags: ["economic-buyer"],
      note: "EB — security-first buyer; wants data-residency guarantees before signing.",
    },
    {
      name: "Karim Haddad",
      title: "Head of Platform",
      company: "HelvetSecure",
      location: "Zurich, CH",
      tags: ["champion"],
      note: "Champion — built the internal business case; sponsor for the pilot.",
    },
    {
      name: "Nadia Petrov",
      title: "Security Engineer",
      company: "HelvetSecure",
      location: "Berlin, DE",
      tags: ["evaluator"],
    },

    // --- Brightwell Health (healthcare, closed-lost) ---
    {
      name: "Dr. Alan Whitmore",
      title: "Chief Medical Information Officer",
      company: "Brightwell Health",
      location: "Boston, MA",
      tags: ["economic-buyer", "closed-lost"],
      note: "Lost — chose incumbent EHR add-on; revisit after their 2-yr contract lapses.",
    },
    {
      name: "Priscilla Adeyemi",
      title: "Head of Ops",
      company: "Brightwell Health",
      location: "Boston, MA",
      tags: ["champion", "closed-lost"],
      note: "Was our champion; frustrated with the outcome, willing to intro elsewhere.",
    },
    {
      name: "Gordon Mackie",
      title: "Compliance Director",
      company: "Brightwell Health",
      location: "Providence, RI",
      tags: ["blocker", "closed-lost"],
      note: "Blocker — HIPAA review stalled the deal past the budget window.",
    },

    // --- Meridian Retail Group (multi-threaded prospect) ---
    {
      name: "Yuki Tanaka",
      title: "VP Digital",
      company: "Meridian Retail Group",
      location: "Seattle, WA",
      tags: ["champion"],
      note: "Champion — wants a fast rollout before holiday peak season.",
    },
    {
      name: "Fernando Cruz",
      title: "CFO",
      company: "Meridian Retail Group",
      location: "Seattle, WA",
      tags: ["economic-buyer"],
    },
    {
      name: "Hannah Berg",
      title: "Head of Store Systems",
      company: "Meridian Retail Group",
      location: "Portland, OR",
      tags: ["evaluator"],
    },
    {
      name: "Ravi Deshpande",
      title: "Procurement Lead",
      company: "Meridian Retail Group",
      location: "Seattle, WA",
      tags: ["blocker"],
      note: "Wants a 3-vendor bake-off; slowing momentum.",
    },

    // --- Aldergrove Bank (financial services) ---
    {
      name: "Eleanor Voss",
      title: "Head of Technology",
      company: "Aldergrove Bank",
      location: "Toronto, ON",
      tags: ["economic-buyer"],
      note: "EB — approval requires board sign-off; long sales cycle.",
    },
    {
      name: "Isaac Mbeki",
      title: "VP Engineering",
      company: "Aldergrove Bank",
      location: "Toronto, ON",
      tags: ["champion"],
    },
    {
      name: "Clara Jensen",
      title: "Risk & Compliance Lead",
      company: "Aldergrove Bank",
      location: "Montreal, QC",
      tags: ["blocker"],
    },
    {
      name: "Peter Ostrowski",
      title: "Solutions Evaluator",
      company: "Aldergrove Bank",
      location: "Toronto, ON",
      tags: ["evaluator"],
    },

    // --- Solvent Manufacturing ---
    {
      name: "Bianca Ferraro",
      title: "COO",
      company: "Solvent Manufacturing",
      location: "Milan, IT",
      tags: ["economic-buyer"],
    },
    {
      name: "Henrik Sørensen",
      title: "Plant Systems Manager",
      company: "Solvent Manufacturing",
      location: "Turin, IT",
      tags: ["champion"],
      note: "Champion — sees ROI in reduced downtime; needs a floor-level demo.",
    },
    {
      name: "Wei Zhang",
      title: "Procurement Lead",
      company: "Solvent Manufacturing",
      location: "Milan, IT",
      tags: ["blocker"],
    },

    // --- Kestrel Aerospace ---
    {
      name: "Colonel Rita Banks",
      title: "Director of Programs",
      company: "Kestrel Aerospace",
      location: "Denver, CO",
      tags: ["economic-buyer"],
      note: "EB — procurement gated by government compliance; ITAR questions open.",
    },
    {
      name: "Samuel Adeyemi",
      title: "Lead Systems Engineer",
      company: "Kestrel Aerospace",
      location: "Denver, CO",
      tags: ["evaluator"],
    },
    {
      name: "Diane Kowalski",
      title: "Head of Ops",
      company: "Kestrel Aerospace",
      location: "Wichita, KS",
      tags: ["champion"],
    },

    // --- Verdant Foods ---
    {
      name: "Olivia Santos",
      title: "VP Supply Chain",
      company: "Verdant Foods",
      location: "Austin, TX",
      tags: ["champion"],
      note: "Champion — moved from Meridian Retail; brings prior product familiarity.",
    },
    {
      name: "Thabo Nkosi",
      title: "CFO",
      company: "Verdant Foods",
      location: "Austin, TX",
      tags: ["economic-buyer"],
    },
    {
      name: "Greta Lindqvist",
      title: "Procurement Lead",
      company: "Verdant Foods",
      location: "Dallas, TX",
      tags: ["evaluator"],
    },

    // --- Pinecrest Insurance ---
    {
      name: "Marcus Webb",
      title: "Chief Digital Officer",
      company: "Pinecrest Insurance",
      location: "Hartford, CT",
      tags: ["economic-buyer"],
    },
    {
      name: "Anjali Rao",
      title: "Head of Claims Tech",
      company: "Pinecrest Insurance",
      location: "Hartford, CT",
      tags: ["champion"],
      note: "Champion — pushing hard internally; wants case studies from insurance peers.",
    },
    {
      name: "Douglas Frey",
      title: "IT Security Lead",
      company: "Pinecrest Insurance",
      location: "New Haven, CT",
      tags: ["blocker"],
    },

    // --- Lumen Media ---
    {
      name: "Camille Dubois",
      title: "VP Product",
      company: "Lumen Media",
      location: "Los Angeles, CA",
      tags: ["champion"],
    },
    {
      name: "Jerome Baptiste",
      title: "CFO",
      company: "Lumen Media",
      location: "Los Angeles, CA",
      tags: ["economic-buyer"],
      note: "EB — cost-sensitive; wants usage-based pricing modeled out.",
    },
    {
      name: "Sasha Ivanova",
      title: "Data Platform Evaluator",
      company: "Lumen Media",
      location: "Remote",
      tags: ["evaluator"],
    },

    // --- Tessellate Analytics (SaaS peer, closed-won) ---
    {
      name: "Nathan Cole",
      title: "CTO",
      company: "Tessellate Analytics",
      location: "San Francisco, CA",
      tags: ["champion", "closed-won"],
      note: "Champion — fast technical win; strong reference customer now.",
    },
    {
      name: "Priyanka Sharma",
      title: "VP Finance",
      company: "Tessellate Analytics",
      location: "San Francisco, CA",
      tags: ["economic-buyer", "closed-won"],
    },
    {
      name: "Leo Nakamura",
      title: "Head of Data Engineering",
      company: "Tessellate Analytics",
      location: "San Jose, CA",
      tags: ["evaluator", "closed-won"],
    },

    // --- Ironbridge Utilities ---
    {
      name: "Fiona Gallagher",
      title: "Director of Grid Operations",
      company: "Ironbridge Utilities",
      location: "Manchester, UK",
      tags: ["economic-buyer"],
    },
    {
      name: "Amara Diallo",
      title: "Head of Ops",
      company: "Ironbridge Utilities",
      location: "Manchester, UK",
      tags: ["champion"],
      note: "Champion — regulatory reporting is her pain; annual budget cycle starts in autumn.",
    },
    {
      name: "Nigel Thornton",
      title: "Procurement Lead",
      company: "Ironbridge Utilities",
      location: "Leeds, UK",
      tags: ["blocker"],
    },

    // --- Harbor & Vale Legal ---
    {
      name: "Beatrice Holloway",
      title: "Managing Partner",
      company: "Harbor & Vale Legal",
      location: "New York, NY",
      tags: ["economic-buyer"],
    },
    {
      name: "Julian Foster",
      title: "Director of Legal Ops",
      company: "Harbor & Vale Legal",
      location: "New York, NY",
      tags: ["champion"],
      note: "Champion — wants to cut document turnaround; changed jobs from Pinecrest, warm intro.",
    },
    {
      name: "Mei Lin Chua",
      title: "IT Evaluator",
      company: "Harbor & Vale Legal",
      location: "New York, NY",
      tags: ["evaluator"],
    },

    // --- Contacts who changed jobs (cross-account relationships) ---
    {
      name: "Victor Almeida",
      title: "VP Engineering",
      company: "Verdant Foods",
      location: "Austin, TX",
      tags: ["champion", "changed-jobs"],
      note: "Changed jobs — was our EB at Northwind, now VP Eng at Verdant; strong warm path in.",
    },
    {
      name: "Sandra Whitfield",
      title: "Head of Ops",
      company: "Meridian Retail Group",
      location: "Portland, OR",
      tags: ["evaluator", "changed-jobs"],
      note: "Changed jobs — moved from Brightwell Health; knows the product from the earlier eval.",
    },
    {
      name: "Ibrahim Toure",
      title: "CFO",
      company: "Ironbridge Utilities",
      location: "London, UK",
      tags: ["economic-buyer", "changed-jobs"],
      note: "Changed jobs — previously CFO at Lumen Media; re-engage with prior pricing context.",
    },

    // --- Partner vendor contacts ---
    {
      name: "Elena Popescu",
      title: "Partner Alliance Manager",
      company: "Coriander Systems Integrators",
      location: "Bucharest, RO",
      tags: ["champion"],
      note: "Co-sell partner — brings us into Aldergrove and Ironbridge deals.",
    },
    {
      name: "David Okoro",
      title: "Delivery Lead",
      company: "Coriander Systems Integrators",
      location: "Lagos, NG",
      tags: ["evaluator"],
    },
    {
      name: "Sophie Laurent",
      title: "Channel Director",
      company: "Ridgeway Cloud Partners",
      location: "Paris, FR",
      tags: ["champion"],
      note: "Reseller — sources cloud-migration deals; introduced HelvetSecure.",
    },
    {
      name: "Tariq Rahman",
      title: "Solutions Consultant",
      company: "Ridgeway Cloud Partners",
      location: "Dubai, AE",
      tags: ["evaluator"],
    },

    // --- A few additional stakeholders to round out threads ---
    {
      name: "Meredith Vance",
      title: "Deputy CFO",
      company: "Cargoline Freight",
      location: "Chicago, IL",
      tags: ["economic-buyer", "closed-won"],
    },
    {
      name: "Oscar Bergström",
      title: "Security Evaluator",
      company: "Aldergrove Bank",
      location: "Stockholm, SE",
      tags: ["evaluator"],
    },
    {
      name: "Lucia Moreno",
      title: "Head of Ops",
      company: "Pinecrest Insurance",
      location: "Hartford, CT",
      tags: ["evaluator"],
    },
    {
      name: "Frank Delgado",
      title: "Procurement Lead",
      company: "Kestrel Aerospace",
      location: "Denver, CO",
      tags: ["blocker"],
    },
    {
      name: "Naomi Kwan",
      title: "VP Engineering",
      company: "Lumen Media",
      location: "Los Angeles, CA",
      tags: ["evaluator"],
    },
  ],
  events: [
    {
      name: "Dhaga Connect 2026 — User Conference",
      emoji: "🎤",
      tags: ["conference", "flagship"],
      attendees: [
        "Dev Malhotra",
        "Sofia Reyes",
        "Karim Haddad",
        "Yuki Tanaka",
        "Nathan Cole",
        "Anjali Rao",
        "Olivia Santos",
        "Elena Popescu",
        "Sophie Laurent",
        "Julian Foster",
      ],
    },
    {
      name: "Cargoline Freight — Quarterly Business Review",
      emoji: "📊",
      tags: ["qbr", "closed-won"],
      attendees: [
        "Dev Malhotra",
        "Sofia Reyes",
        "Grace Okonkwo",
        "Meredith Vance",
        "Aisha Bello",
      ],
    },
    {
      name: "Webinar — Data Residency for Regulated Industries",
      emoji: "🖥️",
      tags: ["webinar", "security"],
      attendees: [
        "Lena Fischer",
        "Karim Haddad",
        "Nadia Petrov",
        "Clara Jensen",
        "Douglas Frey",
        "Oscar Bergström",
        "Gordon Mackie",
      ],
    },
    {
      name: "Meridian Retail — Pre-Holiday Rollout Workshop",
      emoji: "🛍️",
      tags: ["workshop", "prospect"],
      attendees: [
        "Yuki Tanaka",
        "Fernando Cruz",
        "Hannah Berg",
        "Ravi Deshpande",
        "Sandra Whitfield",
      ],
    },
    {
      name: "Partner Co-Sell Roundtable",
      emoji: "🤝",
      tags: ["partner", "co-sell"],
      attendees: [
        "Elena Popescu",
        "David Okoro",
        "Sophie Laurent",
        "Tariq Rahman",
        "Isaac Mbeki",
        "Amara Diallo",
      ],
    },
  ],
});
