import { seedDomainAccount } from "../seed-lib/seed-domain.mjs";

await seedDomainAccount({
  slug: "recruiting",
  displayName: "Tom Bradley — Executive Search (demo)",
  companies: [
    // Employers where candidates currently work
    { name: "Nimbus Data", sector: "Cloud Infrastructure" },
    { name: "Marrow Health", sector: "Digital Health" },
    { name: "Fernwood Labs", sector: "AI / Machine Learning" },
    { name: "Copperline Retail", sector: "E-commerce" },
    { name: "Aster Robotics", sector: "Robotics" },
    { name: "Vellum Media", sector: "Media & Publishing" },
    { name: "Tidewater Analytics", sector: "Data & Analytics" },
    { name: "Harborstone Bank", sector: "Financial Services" },
    // Client companies that hire
    { name: "Kite Financial", sector: "Fintech" },
    { name: "Solaris Grid", sector: "Clean Energy" },
    { name: "Meridian Logistics", sector: "Supply Chain" },
    { name: "Petal & Co.", sector: "Consumer / DTC" },
    { name: "Northwind Security", sector: "Cybersecurity" },
    { name: "Cobalt Studios", sector: "Gaming" },
    { name: "Everest Biosciences", sector: "Biotech" },
    { name: "Lumen Education", sector: "EdTech" },
  ],
  contacts: [
    // ---- Candidates: engineering ----
    { name: "Priya Raghunathan", title: "Senior Backend Engineer", company: "Nimbus Data", location: "Austin, TX", tags: ["candidate", "passive", "open-to-move"], note: "Passive; would move for a remote staff role at the right comp (~$210k)." },
    { name: "Marcus Webb", title: "Staff Software Engineer", company: "Fernwood Labs", location: "San Francisco, CA", tags: ["candidate", "passive"], note: "Deep ML infra background. Not looking now — reconnect Q1." },
    { name: "Elena Vasquez", title: "Engineering Manager", company: "Aster Robotics", location: "Boston, MA", tags: ["candidate", "open-to-move"], note: "Wants first Director role; frustrated with flat org at Aster." },
    { name: "Dele Okafor", title: "Senior Frontend Engineer", company: "Copperline Retail", location: "Chicago, IL", tags: ["candidate", "silver-medalist"], note: "Silver-medalist for the Kite Financial UI role — strong, lost on location." },
    { name: "Hana Kobayashi", title: "Platform Engineer", company: "Tidewater Analytics", location: "Seattle, WA", tags: ["candidate", "passive"] },
    { name: "Samuel Adeyemi", title: "DevOps Engineer", company: "Nimbus Data", location: "Remote", tags: ["candidate", "open-to-move"] },
    { name: "Grace Lin", title: "Backend Engineer", company: "Marrow Health", location: "New York, NY", tags: ["candidate"] },
    { name: "Owen Fitzgerald", title: "Principal Engineer", company: "Harborstone Bank", location: "Charlotte, NC", tags: ["candidate", "passive"], note: "20 yrs in fintech; only moves for a Principal/Architect title bump." },
    { name: "Yara Haddad", title: "Machine Learning Engineer", company: "Fernwood Labs", location: "San Francisco, CA", tags: ["candidate", "open-to-move"] },
    { name: "Tobias Krause", title: "Site Reliability Engineer", company: "Aster Robotics", location: "Denver, CO", tags: ["candidate"] },
    { name: "Amara Nwosu", title: "Full-Stack Engineer", company: "Vellum Media", location: "Atlanta, GA", tags: ["candidate", "open-to-move"] },
    { name: "Rohan Mehta", title: "Data Engineer", company: "Tidewater Analytics", location: "Seattle, WA", tags: ["candidate", "passive"] },

    // ---- Candidates: placed (now at client companies) ----
    { name: "Isabelle Rousseau", title: "Senior Backend Engineer", company: "Kite Financial", location: "New York, NY", tags: ["candidate", "placed"], note: "Placed at Kite Financial 2024 — check in, likely a future client." },
    { name: "David Chen", title: "Engineering Lead", company: "Solaris Grid", location: "Phoenix, AZ", tags: ["candidate", "placed"], note: "Placed 2023 at Solaris Grid; thriving, great referral source." },
    { name: "Nadia Petrova", title: "Product Manager", company: "Meridian Logistics", location: "Dallas, TX", tags: ["candidate", "placed"] },
    { name: "Kwame Boateng", title: "Security Engineer", company: "Northwind Security", location: "Washington, DC", tags: ["candidate", "placed"], note: "Placed early 2025; still in guarantee period — keep close." },
    { name: "Lucia Moretti", title: "Design Lead", company: "Petal & Co.", location: "Los Angeles, CA", tags: ["candidate", "placed"] },

    // ---- Candidates: design & product ----
    { name: "Jonas Berg", title: "Design Lead", company: "Vellum Media", location: "Portland, OR", tags: ["candidate", "passive", "open-to-move"], note: "Portfolio is exceptional; would consider a client-side Head of Design role." },
    { name: "Fatima Al-Rashid", title: "Senior Product Designer", company: "Marrow Health", location: "Remote", tags: ["candidate"] },
    { name: "Theo Laurent", title: "Product Manager", company: "Copperline Retail", location: "Chicago, IL", tags: ["candidate", "silver-medalist"], note: "Silver-medalist for the Cobalt Studios PM role." },
    { name: "Ingrid Solberg", title: "UX Researcher", company: "Tidewater Analytics", location: "Minneapolis, MN", tags: ["candidate", "open-to-move"] },
    { name: "Rafael Santos", title: "Group Product Manager", company: "Nimbus Data", location: "Austin, TX", tags: ["candidate", "passive"] },
    { name: "Mei Zhang", title: "Product Design Manager", company: "Aster Robotics", location: "Boston, MA", tags: ["candidate"] },

    // ---- Candidates: data / ML / other ----
    { name: "Benjamin Ortiz", title: "Data Scientist", company: "Marrow Health", location: "New York, NY", tags: ["candidate", "open-to-move"] },
    { name: "Chloe Dubois", title: "Analytics Lead", company: "Copperline Retail", location: "Chicago, IL", tags: ["candidate", "passive"] },
    { name: "Arjun Kapoor", title: "Head of Data", company: "Harborstone Bank", location: "Charlotte, NC", tags: ["candidate", "passive", "open-to-move"], note: "Exploring quietly; conflict with new CTO. Handle discreetly." },
    { name: "Sofia Andersson", title: "ML Research Scientist", company: "Fernwood Labs", location: "San Francisco, CA", tags: ["candidate", "silver-medalist"], note: "Silver-medalist for the Everest Biosciences ML role — offer went to internal." },

    // ---- Candidates: go-to-market / ops ----
    { name: "James Kelly", title: "VP Sales", company: "Vellum Media", location: "New York, NY", tags: ["candidate", "open-to-move"] },
    { name: "Aisha Bello", title: "Head of Marketing", company: "Copperline Retail", location: "Remote", tags: ["candidate", "passive"] },
    { name: "Viktor Novak", title: "Sales Director", company: "Harborstone Bank", location: "Charlotte, NC", tags: ["candidate"] },
    { name: "Renata Cruz", title: "Chief of Staff", company: "Aster Robotics", location: "Boston, MA", tags: ["candidate", "open-to-move"], note: "Ex-consultant; wants a COO track. Watch for the right seed-stage client." },
    { name: "Liam O'Sullivan", title: "Finance Director", company: "Tidewater Analytics", location: "Seattle, WA", tags: ["candidate"] },
    { name: "Zoe Nakamura", title: "People Operations Lead", company: "Marrow Health", location: "Remote", tags: ["candidate", "passive"] },

    // ---- Candidates: more engineering breadth ----
    { name: "Gabriel Silva", title: "Mobile Engineer", company: "Vellum Media", location: "Miami, FL", tags: ["candidate", "open-to-move"] },
    { name: "Anika Sharma", title: "QA Lead", company: "Copperline Retail", location: "Chicago, IL", tags: ["candidate"] },
    { name: "Felix Bauer", title: "Security Engineer", company: "Nimbus Data", location: "Remote", tags: ["candidate", "silver-medalist"], note: "Silver-medalist for the Northwind Security role; keep warm." },
    { name: "Priscilla Mensah", title: "Data Platform Lead", company: "Tidewater Analytics", location: "Seattle, WA", tags: ["candidate", "passive"] },
    { name: "Mateo Rossi", title: "Backend Engineer", company: "Harborstone Bank", location: "Charlotte, NC", tags: ["candidate", "open-to-move"] },
    { name: "Harper Quinn", title: "Frontend Engineer", company: "Marrow Health", location: "Remote", tags: ["candidate"] },

    // ---- Hiring managers / clients ----
    { name: "Diana Voss", title: "VP People (client)", company: "Kite Financial", location: "New York, NY", tags: ["hiring-manager", "client"], note: "Best client relationship I have. Hires 6–8 eng/yr. Isabelle's manager." },
    { name: "Ethan Brooks", title: "CTO (client)", company: "Kite Financial", location: "New York, NY", tags: ["hiring-manager", "client"] },
    { name: "Naomi Reyes", title: "Head of Talent (client)", company: "Solaris Grid", location: "Phoenix, AZ", tags: ["hiring-manager", "client"], note: "Ramping a new engineering hub — 4 open reqs for Q3." },
    { name: "Oliver Grant", title: "VP Engineering (client)", company: "Solaris Grid", location: "Phoenix, AZ", tags: ["hiring-manager", "client"] },
    { name: "Bianca Costa", title: "Director of Recruiting (client)", company: "Meridian Logistics", location: "Dallas, TX", tags: ["hiring-manager", "client"] },
    { name: "Raymond Ellis", title: "COO (client)", company: "Meridian Logistics", location: "Dallas, TX", tags: ["hiring-manager", "client"] },
    { name: "Sadie Whitfield", title: "Head of People (client)", company: "Petal & Co.", location: "Los Angeles, CA", tags: ["hiring-manager", "client"], note: "First-time hiring exec; needs a lot of hand-holding but loyal." },
    { name: "Gordon Pryce", title: "CISO (client)", company: "Northwind Security", location: "Washington, DC", tags: ["hiring-manager", "client"], note: "Only hires senior security talent; slow process, high bar." },
    { name: "Tanya Iyer", title: "Talent Partner (client)", company: "Northwind Security", location: "Washington, DC", tags: ["hiring-manager", "client"] },
    { name: "Simon Yardley", title: "Studio Head (client)", company: "Cobalt Studios", location: "Austin, TX", tags: ["hiring-manager", "client"], note: "Scaling a new studio; wants senior PMs and gameplay engineers." },
    { name: "Charlotte Meyer", title: "VP People (client)", company: "Everest Biosciences", location: "Cambridge, MA", tags: ["hiring-manager", "client"] },
    { name: "Dr. Alan Frost", title: "Head of R&D (client)", company: "Everest Biosciences", location: "Cambridge, MA", tags: ["hiring-manager", "client"], note: "Tough to place for — very specific ML+biology profile." },
    { name: "Wendy Chukwu", title: "Chief People Officer (client)", company: "Lumen Education", location: "Remote", tags: ["hiring-manager", "client"], note: "New logo, signed 2025. Building out product + eng from scratch." },
    { name: "Paul Hargreaves", title: "Head of Engineering (client)", company: "Lumen Education", location: "Boston, MA", tags: ["hiring-manager", "client"] },
    { name: "Melissa Tan", title: "Talent Acquisition Lead (client)", company: "Kite Financial", location: "New York, NY", tags: ["hiring-manager", "client"] },
    { name: "Hector Alvarez", title: "VP Engineering (client)", company: "Cobalt Studios", location: "Austin, TX", tags: ["hiring-manager", "client"] },
    { name: "Rebecca Stone", title: "Director of People (client)", company: "Petal & Co.", location: "Los Angeles, CA", tags: ["hiring-manager", "client"] },
  ],
  events: [
    {
      name: "Austin Backend Meetup",
      emoji: "🛠️",
      tags: ["meetup", "engineering"],
      attendees: [
        "Priya Raghunathan",
        "Rafael Santos",
        "Samuel Adeyemi",
        "Simon Yardley",
        "Hector Alvarez",
        "Felix Bauer",
      ],
    },
    {
      name: "Spring Tech Career Fair",
      emoji: "🎪",
      tags: ["career-fair", "hiring"],
      attendees: [
        "Dele Okafor",
        "Grace Lin",
        "Amara Nwosu",
        "Gabriel Silva",
        "Anika Sharma",
        "Harper Quinn",
        "Naomi Reyes",
        "Bianca Costa",
        "Melissa Tan",
        "Wendy Chukwu",
      ],
    },
    {
      name: "State University Alumni Night",
      emoji: "🎓",
      tags: ["alumni", "networking"],
      attendees: [
        "Marcus Webb",
        "Yara Haddad",
        "Sofia Andersson",
        "Elena Vasquez",
        "David Chen",
        "Ethan Brooks",
        "Dr. Alan Frost",
        "Charlotte Meyer",
      ],
    },
    {
      name: "Women in Tech Leadership Dinner",
      emoji: "🍽️",
      tags: ["leadership", "networking"],
      attendees: [
        "Renata Cruz",
        "Mei Zhang",
        "Aisha Bello",
        "Diana Voss",
        "Sadie Whitfield",
        "Rebecca Stone",
        "Zoe Nakamura",
      ],
    },
    {
      name: "Cloud & Infra Summit",
      emoji: "☁️",
      tags: ["conference", "engineering"],
      attendees: [
        "Hana Kobayashi",
        "Tobias Krause",
        "Priscilla Mensah",
        "Rohan Mehta",
        "Oliver Grant",
        "Paul Hargreaves",
      ],
    },
    {
      name: "Fintech Hiring Mixer",
      emoji: "💳",
      tags: ["mixer", "fintech", "hiring"],
      attendees: [
        "Isabelle Rousseau",
        "Owen Fitzgerald",
        "Mateo Rossi",
        "Viktor Novak",
        "Arjun Kapoor",
        "Diana Voss",
        "Ethan Brooks",
        "Melissa Tan",
      ],
    },
    {
      name: "Security Leaders Roundtable",
      emoji: "🔐",
      tags: ["roundtable", "security"],
      attendees: [
        "Kwame Boateng",
        "Felix Bauer",
        "Gordon Pryce",
        "Tanya Iyer",
      ],
    },
    {
      name: "Product & Design Portfolio Night",
      emoji: "🎨",
      tags: ["meetup", "design", "product"],
      attendees: [
        "Jonas Berg",
        "Fatima Al-Rashid",
        "Lucia Moretti",
        "Theo Laurent",
        "Ingrid Solberg",
        "Simon Yardley",
      ],
    },
  ],
});
