// Runtime services: the LLM gateway, prompt builders, heuristic parse, web
// search, retrieval/embeddings, and calendar providers. Re-exported from
// index.ts via `export *`.
export {
  AnthropicLLMClient,
  OpenAILLMClient,
  BRIEF_SYSTEM,
  CARD_SCAN_PROMPT,
  CARD_SCAN_SYSTEM,
  CONTACT_PARSE_SYSTEM,
  DRAFT_SYSTEM,
  ENRICHMENT_SYSTEM,
  ENRICHMENT_EXTRACTION_SYSTEM,
  NOTE_EXTRACTION_SYSTEM,
  SEARCH_ANSWER_SYSTEM,
  SEARCH_QUERY_SYSTEM,
  buildBriefPrompt,
  buildContactParsePrompt,
  buildDraftPrompt,
  buildEnrichmentPrompt,
  buildEnrichmentExtractionPrompt,
  buildNoteExtractionPrompt,
  buildSearchAnswerPrompt,
  buildSearchQueryPrompt,
  type BriefContext,
  type DraftContext,
  type EnrichmentSubject,
  type NodeTypeRef,
  getBatchLLMClient,
  getLLMClient,
  getLLMProvider,
  hasBatchLLM,
  hasLLM,
  registerLLMProvider,
  selectLLMProvider,
  type BatchExtractItem,
  type BatchExtractResult,
  type BatchLLMClient,
  type BatchResultStatus,
  type CompleteOptions,
  type ExtractOptions,
  type LLMClient,
  type LLMImage,
  type LLMResult,
  type LLMUsage,
  type LLMProvider,
  type LLMProviderCapabilities,
  type ModelTier,
  type OpenAILLMClientOptions,
} from "./llm";
export {
  SIGNAL_DETECTION_SYSTEM,
  buildSignalDetectionPrompt,
  type SignalDetectionSubject,
} from "./llm/prompts/signal-detection";
export { heuristicContactParse } from "./parse/heuristic-contact";
export {
  FirecrawlSearchClient,
  getSearchClient,
  getSearchProvider,
  hasSearch,
  registerSearchProvider,
  selectSearchProvider,
  type SearchClient,
  type SearchOptions,
  type SearchProvider,
  type SearchResult,
} from "./search";
export {
  assertCompatibleVectorDimensions,
  DEFAULT_EMBEDDING_DIMENSIONS,
  getEmbeddingProvider,
  getVectorStore,
  registerEmbeddingProvider,
  registerVectorStore,
  selectEmbeddingProvider,
  selectVectorStore,
  type EmbeddingProvider,
  type VectorHit,
  type VectorRecord,
  type VectorSearchOptions,
  type VectorStore,
  type VectorWriteOptions,
} from "./retrieval";
export {
  getSearchIndex,
  registerSearchIndex,
  selectSearchIndex,
  type SearchDocument,
  type SearchIndex,
  type SearchIndexResult,
  type SearchKind,
  type SearchQuery,
  type SearchWeights,
  type SearchWriteOptions,
} from "./search-index";
export {
  DemoCalendarProvider,
  GoogleCalendarProvider,
  MicrosoftCalendarProvider,
  buildAddToCalendarLinks,
  buildIcs,
  dayLoad,
  findOpenSlots,
  getCalendarProvider,
  isOverloaded,
  listCalendarProviders,
  listConnectableCalendarProviders,
  mergeBusy,
  registerCalendarProvider,
  spreadAcrossWeek,
  type BusyInterval,
  type CalendarProvider,
  type CalendarProviderInfo,
  type CalendarTokens,
  type DayBucket,
  type DayLoad,
  type OpenSlot,
  type SpreadItem,
  type TimeRange,
  type WorkingHours,
} from "./calendar";
