/**
 * Shared resilience helpers for server actions. A transient DB/connection
 * failure (a momentary pool saturation the connect-retry couldn't ride out, a
 * dropped socket mid-query) must never dump the user into the full-page error
 * boundary or throw away what they just typed. Actions that back a form
 * (useActionState) catch the write and return this message instead of throwing,
 * so the client component stays mounted with the user's unsaved input intact.
 */

import { isTransientConnectionError } from "@/utils/constants/db";

/** User-facing copy for a transient save failure — reassures that input is kept. */
export const SAVE_RETRY_MESSAGE =
  "Something interrupted the save — your details are still here. Please try again.";

/**
 * Message text for PROGRAMMER-ERROR classes only. A TypeError/ReferenceError
 * message is generated by the engine from the shape of the code ("Cannot read
 * properties of undefined (reading 'getTime')", "x is not a function") — it
 * names identifiers and properties, never the values that flowed through them,
 * so it carries no PII. Every other class stays redacted: those are the ones
 * that echo data (a Postgres constraint violation quotes the conflicting value,
 * a SyntaxError from JSON.parse quotes the payload).
 */
function bugMessage(error: unknown): string | undefined {
  if (error instanceof TypeError || error instanceof ReferenceError) return error.message;
  return undefined;
}

/** Top stack frames as `file:line`, message line dropped — see `at` above. */
function stackFrames(error: unknown, limit = 4): string[] | undefined {
  if (!(error instanceof Error) || !error.stack) return undefined;
  const frames = error.stack
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.startsWith("at "))
    .slice(0, limit);
  return frames.length > 0 ? frames : undefined;
}

/**
 * Log a mutation failure to server logs WITHOUT contact PII (privacy rule: never
 * log contact names, note text, or extraction output). Records the action name,
 * the error's `code`/`name`, a `transient` flag, and — only for the classes
 * where it cannot carry data — its `message` and top stack frames.
 *
 * `transient` classifies the error with the same PII-safe predicate the pools
 * retry on (`isTransientConnectionError`: fixed `code`/message checks only): true
 * means a pool connect-timeout / session-pool rejection that a retry rides out —
 * infra, not a bug. Without it a connect-timeout and any other bare `Error` both
 * log as `{ code: undefined, name: 'Error' }`, indistinguishable; the flag is
 * what makes "transient blip" vs "real bug" decidable from the log line alone.
 *
 * `message` (see bugMessage) and `at` (see stackFrames) exist for the same
 * reason and are bounded by the same test — both describe CODE, never values.
 * `{ code: undefined, name: 'TypeError' }` on its own says a bug exists and
 * nothing about where, which is a log line that costs a deploy cycle to act on.
 * Note that `at` is minified in a production build unless server source maps are
 * enabled (`NODE_OPTIONS=--enable-source-maps`), so `message` is usually the
 * part that names the bug.
 */
export function logActionError(action: string, error: unknown): void {
  const code = (error as { code?: unknown } | null)?.code;
  const name = error instanceof Error ? error.name : typeof error;
  const transient = isTransientConnectionError(error);
  console.error(`[action:${action}] failed`, {
    code,
    name,
    transient,
    message: bugMessage(error),
    at: stackFrames(error),
  });
}
