export { ASK_QUERIES, GITHUB_URL, HERO, STATS } from "./hero";
export {
  MOCK_CIRCLES,
  MOCK_CAPTURE_ACTIONS,
  MOCK_FEED,
  MOCK_HOME_PEOPLE,
  MOCK_HOME_EVENTS,
  MOCK_PROFILE_FACTS,
  MOCK_TIMELINE,
} from "./appmock";
export {
  ASK_EXAMPLES,
  COMPARISON_COLUMNS,
  COMPARISON_ROWS,
  HOW_IT_WORKS,
  OSS_PILLARS,
} from "./sections";
export { FAQ_ITEMS, PRICING_PLANS } from "./pricing";
