/**
 * PII-safe error logging fields, shared by the app, packages/core and
 * packages/ee (DEEP-IMPORT-ONLY, like ./messaging — not re-exported from the
 * package root).
 *
 * THE RULE THIS ENCODES: a server log may describe the CODE that failed; it may
 * never describe the VALUES that flowed through it. Contact names, note text,
 * extraction output, message bodies, recipient ids and email addresses are the
 * user's data about third parties (CLAUDE.md privacy rules) and must not reach
 * a log line.
 *
 * WHY A HELPER AND NOT A CONVENTION: the rule was already written down, and
 * `console.error("...", error)` still appeared at eight call sites — two of them
 * directly beneath comments asserting that no PII was logged. Passing a raw
 * Error as console's second argument serializes its `message`, its `stack`, and
 * for SDK errors the attached HTTP response body. A rule that has to be
 * remembered at every call site is a rule that will be broken at one of them, so
 * the safe shape is the one that is easiest to reach for.
 *
 * USE: `console.error("[label] what failed", { ...errorFields(error), count })`
 */

/** The error's constructor name, or the typeof for a non-Error throw. */
function errorName(error: unknown): string {
  return error instanceof Error ? error.name : typeof error;
}

/**
 * A driver/provider error code — Postgres SQLSTATE ("23505"), libuv ("ECONNREFUSED"),
 * a provider's own enum. Always a fixed symbol from a closed vocabulary, never
 * user data, so it is safe unconditionally.
 */
function errorCode(error: unknown): unknown {
  return (error as { code?: unknown } | null)?.code;
}

/**
 * Message text for PROGRAMMER-ERROR classes only. A TypeError/ReferenceError
 * message is generated by the engine from the shape of the code ("Cannot read
 * properties of undefined (reading 'getTime')", "x is not a function"), so it
 * names identifiers and properties — never the values that flowed through them.
 *
 * Every other class stays redacted, because those are the ones that echo data:
 * a Postgres constraint violation quotes the conflicting value, an SDK error
 * carries the request payload, and — the case that matters most here — a
 * SyntaxError from JSON.parse quotes the offending input, which on an inbound
 * webhook IS the message body. Do not widen this predicate to SyntaxError.
 */
export function bugMessage(error: unknown): string | undefined {
  if (error instanceof TypeError || error instanceof ReferenceError) return error.message;
  return undefined;
}

/**
 * Top stack FRAMES with the message line dropped. A frame is a code location
 * (file, line, function), so it says WHERE without saying what. Minified in a
 * production build unless server source maps are enabled
 * (`NODE_OPTIONS=--enable-source-maps`).
 */
export function stackFrames(error: unknown, limit = 4): string[] | undefined {
  if (!(error instanceof Error) || !error.stack) return undefined;
  const frames = error.stack
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.startsWith("at "))
    .slice(0, limit);
  return frames.length > 0 ? frames : undefined;
}

/** Every PII-safe field an error can contribute, ready to spread into a log object. */
export function errorFields(error: unknown): {
  name: string;
  code: unknown;
  message: string | undefined;
  at: string[] | undefined;
} {
  return {
    name: errorName(error),
    code: errorCode(error),
    message: bugMessage(error),
    at: stackFrames(error),
  };
}

/**
 * An HTTP status carried by a provider SDK error (Stripe `statusCode`, fetch-shaped
 * `status`). The single most useful field for a provider failure — it separates
 * "they rejected us" from "they were down" — and it is a number, so it is safe.
 */
export function providerStatus(error: unknown): number | undefined {
  const candidate = error as { status?: unknown; statusCode?: unknown } | null;
  const status = candidate?.status ?? candidate?.statusCode;
  return typeof status === "number" ? status : undefined;
}
