import { loader } from "fumadocs-core/source";
import { blog } from "../../.source/server";

// The Fumadocs source for `/blog` — the engineering blog. `.source` is
// generated by `fumadocs-mdx` from `source.config.ts`; `loader()` turns it into
// the page tree + page lookups the blog route and layout consume. Mirrors
// `src/lib/source.ts` (the `/docs` source), pointed at the `blog` collection.
export const blogSource = loader({
  baseUrl: "/blog",
  source: blog.toFumadocsSource(),
});
