import { loader } from "fumadocs-core/source";
import { docs } from "../../.source/server";

// The single Fumadocs source for `/docs`. `.source` is generated by
// `fumadocs-mdx` from `source.config.ts`; `loader()` turns it into the page
// tree + page lookups the docs route and layout consume.
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
